// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWCjSturwPSWXmA8Llqj-5PRQoc11WRg',
    appId: '1:1015109380874:web:744b01bd44978699e0a8f3',
    messagingSenderId: '1015109380874',
    projectId: 'the-first-cometchat-app',
    authDomain: 'the-first-cometchat-app.firebaseapp.com',
    storageBucket: 'the-first-cometchat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqEgIK8QxrnupOOqhMj8R9HJYrd2KSTx8',
    appId: '1:1015109380874:android:c0778d2ff5a716cde0a8f3',
    messagingSenderId: '1015109380874',
    projectId: 'the-first-cometchat-app',
    storageBucket: 'the-first-cometchat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdqKhwz7RrZ5NP2Dmaag97euIGp_WrDd0',
    appId: '1:1015109380874:ios:dbc7da18aeb0992fe0a8f3',
    messagingSenderId: '1015109380874',
    projectId: 'the-first-cometchat-app',
    storageBucket: 'the-first-cometchat-app.firebasestorage.app',
    iosBundleId: 'com.cometchat.demoapp.swift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdqKhwz7RrZ5NP2Dmaag97euIGp_WrDd0',
    appId: '1:1015109380874:ios:5f6086adea1155bfe0a8f3',
    messagingSenderId: '1015109380874',
    projectId: 'the-first-cometchat-app',
    storageBucket: 'the-first-cometchat-app.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeWCjSturwPSWXmA8Llqj-5PRQoc11WRg',
    appId: '1:1015109380874:web:63c5f93aaf39a45ae0a8f3',
    messagingSenderId: '1015109380874',
    projectId: 'the-first-cometchat-app',
    authDomain: 'the-first-cometchat-app.firebaseapp.com',
    storageBucket: 'the-first-cometchat-app.firebasestorage.app',
  );

}